entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

  ping:
    address: ":8082"

certificatesResolvers:
  letsencrypt:
    acme:
      httpChallenge:
        entryPoint: web
      storage: /letsencrypt/acme.json
      email: ops@nlightn.in

providers:
  file:
    directory: /etc/traefik/providers/

ping:
  entryPoint: "ping"
